// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDetS0TyjiXTPu9nLH5Pk4xTaaiVMv2jEI',
    appId: '1:536073911138:web:8534b76f70c82b69760a3b',
    messagingSenderId: '536073911138',
    projectId: 'veloura-21064',
    authDomain: 'veloura-21064.firebaseapp.com',
    storageBucket: 'veloura-21064.firebasestorage.app',
    measurementId: 'G-HEXBPLYNN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCilCC3hZkaQ08rtaelHtJigAoFmL0To0',
    appId: '1:536073911138:android:2287329aa686943f760a3b',
    messagingSenderId: '536073911138',
    projectId: 'veloura-21064',
    storageBucket: 'veloura-21064.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEQSrAf_yNZX5FfIOEIik8YudkIdFUSDE',
    appId: '1:536073911138:ios:f85db00055979889760a3b',
    messagingSenderId: '536073911138',
    projectId: 'veloura-21064',
    storageBucket: 'veloura-21064.firebasestorage.app',
    iosBundleId: 'com.example.veloura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEQSrAf_yNZX5FfIOEIik8YudkIdFUSDE',
    appId: '1:536073911138:ios:f85db00055979889760a3b',
    messagingSenderId: '536073911138',
    projectId: 'veloura-21064',
    storageBucket: 'veloura-21064.firebasestorage.app',
    iosBundleId: 'com.example.veloura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDetS0TyjiXTPu9nLH5Pk4xTaaiVMv2jEI',
    appId: '1:536073911138:web:4028661427167bd9760a3b',
    messagingSenderId: '536073911138',
    projectId: 'veloura-21064',
    authDomain: 'veloura-21064.firebaseapp.com',
    storageBucket: 'veloura-21064.firebasestorage.app',
    measurementId: 'G-ZTBYE10ZV3',
  );
}
